const LINES = ['8라인','9라인','10라인','11라인','12라인','13라인'];
const DEFAULT_PRODUCT_BY_LINE = {'8라인':'N87(대)','9라인':'N86(대)','10라인':'NCA','11라인':'N86(단)','12라인':'N86(대)','13라인':'N86(대)'};
const PRODUCT_OPTIONS = ['N87(대)','N86(대)','N86(단)','NCA'];
const PRODUCT_TEMPLATES = {
  'N87(대)': {cfa:2660,cda:1040,enabled:{pre:true,mainA:true,mainB:true,heat:true},conditions:{pre:{fillTop:4.3,fillMid:4.3,fillBottom:4.3,time:9,temp:630},mainA:{fillTop:6.8,fillMid:4.3,fillBottom:6.3,time:18,temp:775},heat:{fillTop:6,fillMid:6,fillBottom:6,time:9.6,temp:350}}},
  'N86(대)': {cfa:0,cda:940,enabled:{pre:false,mainA:true,mainB:true,heat:true},conditions:{mainA:{fillTop:6.2,fillMid:4,fillBottom:5.7,time:16,temp:797},heat:{fillTop:7.5,fillMid:5.5,fillBottom:6.5,time:9.6,temp:320}}},
  'N86(단)': {cfa:2800,cda:0,enabled:{pre:true,mainA:true,mainB:true,heat:true},conditions:{pre:{fillTop:3.8,fillMid:3.8,fillBottom:3.8,time:13.1,temp:700},mainA:{fillTop:4.8,fillMid:3.3,fillBottom:3.5,time:20,temp:810},heat:{fillTop:5.5,fillMid:3.5,fillBottom:4.5,time:12,temp:720}}},
  'NCA': {cfa:0,cda:0,enabled:{pre:false,mainA:true,mainB:true,heat:true},conditions:{mainA:{fillTop:6.3,fillMid:4.4,fillBottom:5.8,time:18,temp:760},heat:{fillTop:8.2,fillMid:6.2,fillBottom:8.7,time:15.6,temp:710}}}
};
const YIELD_BY_LINE = {
  '8라인': {product:'N87(대)', batchBase:2200, washTheory:0.9964, washProcess:0.99, heatTheory:0.9964, heatProcess:0.994, additives:[{name:'붕산',kg:12.89}]},
  '9라인': {product:'N86(대)', batchBase:2400, washTheory:0.9957, washProcess:0.98, heatTheory:0.9964, heatProcess:0.99, additives:[{name:'붕산',kg:13.76}]},
  '10라인': {product:'NCA', batchBase:2600, washTheory:0.984, washProcess:0.973, heatTheory:0.995, heatProcess:0.976, additives:[{name:'산화지르코늄',kg:1.524},{name:'수산화리튬',kg:63.36}]},
  '11라인': {product:'N86(단)', batchBase:2000, washTheory:1, washProcess:1, heatTheory:0.998, heatProcess:0.985, additives:[{name:'수산화알루미늄',kg:2.89},{name:'수산화코발트',kg:38.1}]},
  '12라인': {product:'N86(대)', batchBase:2400, washTheory:0.9957, washProcess:0.98, heatTheory:0.9964, heatProcess:0.99, additives:[{name:'붕산',kg:13.76}]},
  '13라인': {product:'N86(대)', batchBase:2400, washTheory:0.9957, washProcess:0.98, heatTheory:0.9964, heatProcess:0.99, additives:[{name:'붕산',kg:13.76}]}
};
const PROCESSES = [
  {key:'pre', name:'예비소성', inlet:50, outlet:55, medians:[1078,26225,29824], ranges:['0~21,039','21,039~28,749','28,749 초과']},
  {key:'mainA', name:'본소성A', inlet:20, outlet:60, medians:[4777,11274,13897], ranges:['0~8,799','8,799~12,175','12,175 초과']},
  {key:'mainB', name:'본소성B', inlet:20, outlet:60, medians:[7130.25,13015,17089], ranges:['0~12,094','12,094~15,403','15,403 초과']},
  {key:'heat', name:'열처리', inlet:20, outlet:60, medians:[5654,6375.5,8313.55], ranges:['0~6,025','6,025~6,852','6,852 초과']}
];
const INPUT_PROCESSES = [
  PROCESSES[0],
  {...PROCESSES[1], inputName:'본소성A/B'},
  PROCESSES[3]
];
const DEFAULT_PRODUCTS = ['제품 A','제품 B','제품 C'];
const STORAGE_KEY = 'power-allocation-workspace-v4-default-process-conditions';
const YIELD_SETTINGS_KEY = 'power-allocation-yield-settings-v1';
const PRODUCT_SETTINGS_KEY = 'power-allocation-product-conditions-v1';
const AUX_DAILY_KWH = {'8라인':12112.7,'9라인':11587.3,'10라인':11222.1,'11라인':8091.9,'12라인':11048.2,'13라인':13338.7};
const DEFAULT_LINE_CONFIG = {
  '8라인': {cfa:2660,cda:1040,enabled:{pre:true,mainA:true,mainB:true,heat:true},conditions:{pre:{fillTop:4.3,fillMid:4.3,fillBottom:4.3,time:9,temp:630},mainA:{fillTop:6.8,fillMid:4.3,fillBottom:6.3,time:18,temp:775},heat:{fillTop:6,fillMid:6,fillBottom:6,time:9.6,temp:350}}},
  '9라인': {cfa:0,cda:940,enabled:{pre:false,mainA:true,mainB:true,heat:true},conditions:{mainA:{fillTop:6.2,fillMid:4,fillBottom:5.7,time:16,temp:797},heat:{fillTop:7.5,fillMid:5.5,fillBottom:6.5,time:9.6,temp:320}}},
  '10라인': {cfa:0,cda:0,enabled:{pre:false,mainA:true,mainB:true,heat:true},conditions:{mainA:{fillTop:6.3,fillMid:4.4,fillBottom:5.8,time:18,temp:760},heat:{fillTop:8.2,fillMid:6.2,fillBottom:8.7,time:15.6,temp:710}}},
  '11라인': {cfa:2800,cda:0,enabled:{pre:true,mainA:true,mainB:true,heat:true},conditions:{pre:{fillTop:3.8,fillMid:3.8,fillBottom:3.8,time:13.1,temp:700},mainA:{fillTop:4.8,fillMid:3.3,fillBottom:3.5,time:20,temp:810},heat:{fillTop:5.5,fillMid:3.5,fillBottom:4.5,time:12,temp:720}}},
  '12라인': {cfa:0,cda:940,enabled:{pre:false,mainA:true,mainB:true,heat:true},conditions:{mainA:{fillTop:6.2,fillMid:4,fillBottom:5.7,time:16,temp:797},heat:{fillTop:7.5,fillMid:5.5,fillBottom:6.5,time:9.6,temp:320}}},
  '13라인': {cfa:0,cda:940,enabled:{pre:false,mainA:true,mainB:true,heat:true},conditions:{mainA:{fillTop:6.2,fillMid:4,fillBottom:5.7,time:16,temp:797},heat:{fillTop:7.5,fillMid:5.5,fillBottom:6.5,time:9.6,temp:320}}}
};
const palette = ['#244a70','#e1a12b','#58a57a','#cf5b5b','#8c6db1','#5b8eaa'];
const TARIFF_CHARGE_POWER = {'01':52123,'02':52123,'03':51842,'04':52123,'05':52117,'06':52123,'07':51536,'08':42578,'09':49324,'10':49323,'11':49323,'12':49323};
const TARIFF_RATES = {여름:{중간부하:174.8,최대부하:239.1,경부하:127.6},봄:{중간부하:144.8,최대부하:161.9,경부하:127.6},가을:{중간부하:144.8,최대부하:161.9,경부하:127.6},겨울:{중간부하:174.8,최대부하:214.1,경부하:134.6}};
const TARIFF_SHARES = {중간부하:0.32,최대부하:0.18,경부하:0.5};
let modelSettings = loadSettings();
let yieldSettings = loadYieldSettings();
let productSettings = loadProductSettings();
let records = [];
let lastResult = null;

function loadSettings(){
  try { return {...Object.fromEntries(PROCESSES.map(p=>[p.key,{medians:[...p.medians]}])), ...(JSON.parse(localStorage.getItem('power-model-settings-v2')||'{}'))}; } catch { return Object.fromEntries(PROCESSES.map(p=>[p.key,{medians:[...p.medians]}])); }
}
function loadYieldSettings(){try{const saved=JSON.parse(localStorage.getItem(YIELD_SETTINGS_KEY)||'null');return Object.fromEntries(LINES.map(line=>[line,{...(YIELD_BY_LINE[line]||{}),...(saved?.[line]||{}),additives:saved?.[line]?.additives??JSON.parse(JSON.stringify(YIELD_BY_LINE[line]?.additives||[]))}]))}catch{return JSON.parse(JSON.stringify(YIELD_BY_LINE))}}
function saveYieldSettings(){localStorage.setItem(YIELD_SETTINGS_KEY,JSON.stringify(yieldSettings))}
function loadProductSettings(){try{const saved=JSON.parse(localStorage.getItem(PRODUCT_SETTINGS_KEY)||'null');return Object.fromEntries(PRODUCT_OPTIONS.map(product=>{const base=JSON.parse(JSON.stringify(PRODUCT_TEMPLATES[product]));const override=saved?.[product]||{};return [product,{...base,...override,conditions:{...base.conditions,...(override.conditions||{})}}]}))}catch{return JSON.parse(JSON.stringify(PRODUCT_TEMPLATES))}}
function saveProductSettings(){localStorage.setItem(PRODUCT_SETTINGS_KEY,JSON.stringify(productSettings))}
function getYieldConfig(rec){return yieldSettings[rec.line]||YIELD_BY_LINE[rec.line]||{batchBase:1,washTheory:1,washProcess:1,heatTheory:1,heatProcess:1,additives:[]}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({month:monthPicker.value,lines:getLineState(),records}));}
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}}
function seasonFromMonth(month){const m=Number((month||'2026-07').split('-')[1]);return m>=3&&m<=5?'봄':m>=6&&m<=8?'여름':m>=9&&m<=11?'가을':'겨울'}
function daysInclusive(start,end,month){const s=new Date(`${start}T00:00:00`), e=new Date(`${end}T00:00:00`);const ms=new Date(`${month}-01T00:00:00`);const me=new Date(ms.getFullYear(),ms.getMonth()+1,0);const a=s<ms?ms:s,b=e>me?me:e;return a>b?0:Math.floor((b-a)/86400000)+1}
function dateSet(start,end,month){const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`),ms=new Date(`${month}-01T00:00:00`),me=new Date(ms.getFullYear(),ms.getMonth()+1,0),a=s<ms?ms:s,b=e>me?me:e,set=new Set();for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))set.add(d.toISOString().slice(0,10));return set}
const HEAT_LEAD_DAYS=2;
function daysBetweenInclusive(start,end){const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`);return s>e?0:Math.floor((e-s)/86400000)+1}
function fullDateSet(start,end){const s=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`),set=new Set();for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1))set.add(d.toISOString().slice(0,10));return set}
const PROCESS_LAG_DAYS={pre:3,mainA:2,mainB:2,heat:1};
// 공무동 RAW 데이터에서 가동라인 수가 0인 행의 계절별 설비 평균값.
// 가동라인이 없는 날에는 분류모델을 호출하지 않고 이 기본전력을 적용한다.
const BASE_UTILITY_DAILY={
  '봄':{ 'Air Compressor':62616.65, '냉동식 Dryer':11215.79, '흡착식 Dryer':10197.05, 'CO2 Removal':19621.14 },
  '여름':{ 'Air Compressor':42908.48, '냉동식 Dryer':10765.15, '흡착식 Dryer':25520.29, 'CO2 Removal':21614.88 },
  '가을':{ 'Air Compressor':67182.19, '냉동식 Dryer':13993.59, '흡착식 Dryer':14283.80, 'CO2 Removal':26883.99 },
  '겨울':{ 'Air Compressor':48263.90, '냉동식 Dryer':6916.38, '흡착식 Dryer':8089.73, 'CO2 Removal':3460.78 }
};
// RAW에서 가동라인 수가 0인 날짜를 월별로 집계한 기준값.
// 해당 월의 무가동 실적이 있으면 월 기준값을 우선 사용하고,
// 없으면 위 계절 기준값으로 보완한다.
const BASE_UTILITY_MONTHLY={
  '01':{ 'Air Compressor':60417.72, '냉동식 Dryer':7733.79, '흡착식 Dryer':13081.75, 'CO2 Removal':0 },
  '02':{ 'Air Compressor':27614.90, '냉동식 Dryer':5534.13, '흡착식 Dryer':0, 'CO2 Removal':0 },
  '03':{ 'Air Compressor':46405.58, '냉동식 Dryer':9265.58, '흡착식 Dryer':0, 'CO2 Removal':0 },
  '05':{ 'Air Compressor':75013.36, '냉동식 Dryer':12707.12, '흡착식 Dryer':17994.79, 'CO2 Removal':34625.55 },
  '06':{ 'Air Compressor':31649.68, '냉동식 Dryer':12615.10, '흡착식 Dryer':29497.96, 'CO2 Removal':25826.20 },
  '07':{ 'Air Compressor':71944.32, '냉동식 Dryer':5994.21, '흡착식 Dryer':15262.07, 'CO2 Removal':10754.11 },
  '11':{ 'Air Compressor':67182.19, '냉동식 Dryer':13993.59, '흡착식 Dryer':14283.80, 'CO2 Removal':26883.99 },
  '12':{ 'Air Compressor':63756.47, '냉동식 Dryer':7944.32, '흡착식 Dryer':13609.73, 'CO2 Removal':19167.42 }
};
function baseUtilityForDay(day){return BASE_UTILITY_MONTHLY[day.slice(5,7)]||BASE_UTILITY_DAILY[seasonFromMonth(day)]}
// 집진기 시트의 20 kWh 초과 일평균값. 9·10라인, 11·12라인은 시트의 공용 설비값을 함께 사용한다.
const DUST_DAILY_KWH={
  '8라인':3050.19,
  '9라인':5100.02,
  '10라인':5100.02,
  '11라인':5100.19,
  '12라인':5100.19,
  '13라인':3049.87
};
function shiftedDateKey(day,offset){const d=new Date(`${day}T00:00:00`);d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
function monthlyHeatDischargeQuantity(rec,month){
  const totalDays=daysBetweenInclusive(rec.start,rec.end);
  if(!totalDays||!Number(rec.qty||0))return 0;
  const s=new Date(`${rec.start}T00:00:00`),e=new Date(`${rec.end}T00:00:00`),monthStart=new Date(`${month}-01T00:00:00`),monthEnd=new Date(monthStart.getFullYear(),monthStart.getMonth()+1,0);
  let dischargeDays=0;
  for(let d=new Date(s);d<=e;d.setDate(d.getDate()+1)){
    const discharge=new Date(d);discharge.setDate(discharge.getDate()+HEAT_LEAD_DAYS);
    if(discharge>=monthStart&&discharge<=monthEnd)dischargeDays+=1;
  }
  return estimateHeatQuantity(rec)*(dischargeDays/totalDays);
}
function fmt(n,dec=1){return Number(n||0).toLocaleString('ko-KR',{maximumFractionDigits:dec,minimumFractionDigits:dec})}
function calculateTariff(month,kwh){const monthKey=String(month||'').slice(5,7),season=seasonFromMonth(month),rates=TARIFF_RATES[season],weightedRate=Object.entries(TARIFF_SHARES).reduce((s,[load,share])=>s+share*rates[load],0),chargePower=TARIFF_CHARGE_POWER[monthKey]||0,baseCharge=7380*chargePower,usageCharge=Number(kwh||0)*weightedRate,climateCharge=Number(kwh||0)*5,fuelCharge=Number(kwh||0)*9,subtotal=baseCharge+usageCharge+climateCharge+fuelCharge,fund=Math.floor(subtotal*0.027/10)*10,vat=subtotal*0.1;return {season,monthKey,chargePower,weightedRate,baseCharge,usageCharge,climateCharge,fuelCharge,subtotal,fund,vat,total:subtotal+fund+vat}}
function formatQuantity(n){const value=String(n??0).replace(/,/g,'');return Number(value||0).toLocaleString('ko-KR',{maximumFractionDigits:0})}
function formatFlow(n){const value=String(n??0).replace(/,/g,'');const number=Number(value||0);return Number.isFinite(number)?number.toLocaleString('ko-KR',{maximumFractionDigits:1}):'0'}
function estimateBatchCount(rec){const y=getYieldConfig(rec),qty=Number(rec.qty||0);return qty>0?Math.ceil(qty/Number(y.batchBase||1)):0}
function estimateHeatQuantity(rec){const y=getYieldConfig(rec),qty=Number(rec.qty||0),washQty=qty*y.washTheory*y.washProcess,additives=(y.additives||[]).reduce((s,a)=>s+Number(a.kg||0),0)*estimateBatchCount(rec),heatInput=washQty+additives;return heatInput*y.heatTheory*y.heatProcess}
function getLineState(){return Object.fromEntries(LINES.map(line=>{const activeEl=document.querySelector(`[data-production-active="${line}"]`)||document.querySelector(`#active-${line}`),productEl=document.querySelector(`[data-line-record-product="${line}"]`)||document.querySelector(`#product-${line}`),cfaEl=document.querySelector(`[data-flow-line="${line}"][data-flow="cfa"]`)||document.querySelector(`#cfa-${line}`),cdaEl=document.querySelector(`[data-flow-line="${line}"][data-flow="cda"]`)||document.querySelector(`#cda-${line}`);return [line,{active:activeEl?.checked??false,product:productEl?.value||DEFAULT_PRODUCT_BY_LINE[line],cfa:Number(String(cfaEl?.value||0).replace(/,/g,''))||0,cda:Number(String(cdaEl?.value||0).replace(/,/g,''))||0}]}))}
function cloneProductTemplate(product){const source=productSettings[product]||PRODUCT_TEMPLATES[product]||PRODUCT_TEMPLATES[PRODUCT_OPTIONS[0]];const conditions={};PROCESSES.forEach(p=>{const c=source.conditions[p.key]||source.conditions.mainA||{fillTop:4.3,fillMid:4.3,fillBottom:4.3,time:9,temp:630};conditions[p.key]={...c,fill:(Number(c.fillTop||0)+Number(c.fillMid||0)+Number(c.fillBottom||0))/3}});return {product,cfa:source.cfa,cda:source.cda,enabled:{...source.enabled},conditions}}
function applyProductToLine(line,product){const state=cloneProductTemplate(product);const cfa=document.getElementById(`cfa-${line}`)||document.querySelector(`[data-flow-line="${line}"][data-flow="cfa"]`),cda=document.getElementById(`cda-${line}`)||document.querySelector(`[data-flow-line="${line}"][data-flow="cda"]`);if(cfa)cfa.value=formatFlow(state.cfa);if(cda)cda.value=formatFlow(state.cda);records.filter(r=>r.line===line).forEach(r=>{r.product=product;r.newProductTest=false;r.enabled={...r.enabled,...state.enabled};r.conditions=JSON.parse(JSON.stringify(state.conditions))});saveState();renderRecords();renderConditions()}
function renderLines(saved={}){lineGrid.innerHTML=LINES.map(line=>{const base=DEFAULT_LINE_CONFIG[line]||{cfa:0,cda:0};const s=saved[line]||{active:false,product:DEFAULT_PRODUCT_BY_LINE[line],cfa:base.cfa,cda:base.cda};const product=s.product||DEFAULT_PRODUCT_BY_LINE[line];return `<div class="line-card ${s.active?'active':''}" data-line-card="${line}"><div class="line-card-header"><span class="line-name">${line}</span><label class="switch"><input type="checkbox" id="active-${line}" ${s.active?'checked':''}> 가동</label></div><label class="field-label">제품명</label><select class="record-select line-product-select" id="product-${line}" data-line-product="${line}">${PRODUCT_OPTIONS.map(p=>`<option value="${p}" ${p===product?'selected':''}>${p}</option>`).join('')}</select><label class="field-label">CFA 유량 (Nm³/hr)</label><input class="mini-input" id="cfa-${line}" type="text" inputmode="decimal" value="${formatFlow(s.cfa??base.cfa)}"><label class="field-label">CDA 유량 (Nm³/hr)</label><input class="mini-input" id="cda-${line}" type="text" inputmode="decimal" value="${formatFlow(s.cda??base.cda)}"></div>`}).join('');document.querySelectorAll('[data-line-card] input').forEach(i=>i.addEventListener('change',()=>{i.closest('.line-card').classList.toggle('active',i.type==='checkbox'&&i.checked);if(i.type==='checkbox'){const mirror=document.querySelector(`[data-production-active="${i.id.replace('active-','')}"]`);if(mirror)mirror.checked=i.checked;productionCards.querySelector(`[data-production-line="${i.id.replace('active-','')}"]`)?.classList.toggle('active',i.checked);renderConditions()}saveState()}));document.querySelectorAll('[data-line-card] .line-product-select').forEach(i=>i.addEventListener('change',()=>applyProductToLine(i.dataset.lineProduct,i.value)));document.querySelectorAll('[data-line-card] .mini-input').forEach(i=>{i.addEventListener('input',()=>{saveState();renderRecords()});i.addEventListener('blur',()=>{i.value=formatFlow(i.value);saveState();renderRecords()})})}
function blankRecord(line='8라인'){const state=getLineState()[line]||{},product=state.product||DEFAULT_PRODUCT_BY_LINE[line]||'제품명 입력',template=cloneProductTemplate(product);return {id:crypto.randomUUID(),line,product,start:`${monthPicker.value}-01`,end:`${monthPicker.value}-${String(new Date(Number(monthPicker.value.slice(0,4)),Number(monthPicker.value.slice(5))-1,0).getDate()).padStart(2,'0')}`,qty:0,enabled:{...template.enabled},conditions:template.conditions}}
function normalizeRecords(list){return list.map(r=>{r.conditions=r.conditions||{};PROCESSES.forEach(p=>{const c=r.conditions[p.key]||{};const legacy=Number(c.fill??4.3);c.fillTop=Number(c.fillTop??legacy);c.fillMid=Number(c.fillMid??legacy);c.fillBottom=Number(c.fillBottom??legacy);c.fill=(c.fillTop+c.fillMid+c.fillBottom)/3;c.time=Number(c.time??9);c.temp=Number(c.temp??630);r.conditions[p.key]=c});r.enabled={...Object.fromEntries(PROCESSES.map(p=>[p.key,true])),...(r.enabled||{})};return r})}
function renderRecords(){
  const lineState=getLineState();
  productionCards.innerHTML=LINES.map(line=>{
    const lineRecords=records.filter(r=>r.line===line);
    const active=lineState[line]?.active??false;
     const recordHtml=lineRecords.map(r=>`<div class="production-record" data-id="${r.id}"><div class="production-record-grid"><div class="wide"><label class="field-label">제품명</label><select class="record-select" data-line-record-product="${line}">${PRODUCT_OPTIONS.map(p=>`<option value="${p}" ${p===r.product?'selected':''}>${p}</option>`).join('')}</select></div><div><label class="field-label">열처리 배출 시작일</label><input class="record-input" data-f="start" type="date" value="${r.start}"></div><div><label class="field-label">열처리 배출 종료일</label><input class="record-input" data-f="end" type="date" value="${r.end}"></div><div class="wide"><label class="field-label">열처리 생산량 (kg)</label><input class="record-input" data-f="qty" type="number" min="0" step="1" value="${r.qty}"></div></div><div class="production-processes"><span class="production-record-label">운전 공정</span>${INPUT_PROCESSES.map(p=>`<label class="process-check"><input type="checkbox" data-process="${p.key}" ${((p.key==='mainA'?r.enabled.mainA&&r.enabled.mainB:r.enabled[p.key]))?'checked':''}> ${p.inputName||p.name}</label>`).join('')}</div><div class="production-record-actions"><span class="production-record-label">입력 열처리 생산량</span><button class="row-delete" data-delete="${r.id}">기록 삭제</button></div></div>`).join('');
    const flowSummary=`<div class="production-flow-summary"><label>CFA 유량 <input class="flow-input" data-flow-line="${line}" data-flow="cfa" type="text" inputmode="decimal" value="${formatFlow(lineState[line]?.cfa||0)}"><span>Nm³/hr</span></label><label>CDA 유량 <input class="flow-input" data-flow-line="${line}" data-flow="cda" type="text" inputmode="decimal" value="${formatFlow(lineState[line]?.cda||0)}"><span>Nm³/hr</span></label></div>`;
    return `<div class="production-line-card ${active?'active':'inactive'}" data-production-line="${line}"><div class="production-line-header"><span class="production-line-title">${line}</span><label class="switch"><input type="checkbox" data-production-active="${line}" ${active?'checked':''}> 가동</label></div>${flowSummary}${recordHtml||'<p class="muted">등록된 생산기록이 없습니다.</p>'}<button class="production-add" data-add-line="${line}">+ ${line} 생산기록 추가</button></div>`;
  }).join('');
  productionCards.querySelectorAll('.production-record').forEach(card=>{const r=records.find(x=>x.id===card.dataset.id);r.bimodal=Boolean(r.bimodal);const label=document.createElement('label');label.className='process-check bimodal-check';label.innerHTML=`<input type="checkbox" data-bimodal ${r.bimodal?'checked':''}> Bimodal`;card.querySelector('.production-processes').appendChild(label)});
  productionCards.querySelectorAll('.production-record').forEach(card=>{const button=document.createElement('button');button.type='button';button.className='new-product-test';button.dataset.newProductTest=card.dataset.id;button.textContent='신제품 TEST 조회';card.querySelector('.wide')?.prepend(button)});
  productionCards.querySelectorAll('[data-f="qty"]').forEach(el=>{el.type='text';el.inputMode='numeric';el.value=formatQuantity(el.value);el.addEventListener('input',()=>{const cursor=el.selectionStart??el.value.length,rawBefore=el.value.slice(0,cursor).replace(/\D/g,''),raw=el.value.replace(/\D/g,'');el.value=Number(raw||0).toLocaleString('ko-KR',{maximumFractionDigits:0});let next=el.value.length,digits=0;for(let i=0;i<el.value.length;i++){if(/\d/.test(el.value[i]))digits++;if(digits>=rawBefore.length){next=i+1;break}}el.setSelectionRange(next,next)},{capture:true});el.addEventListener('blur',()=>{el.value=formatQuantity(el.value)})});
  productionCards.querySelectorAll('[data-f]').forEach(el=>el.addEventListener('input',()=>{const r=records.find(x=>x.id===el.closest('.production-record').dataset.id);r[el.dataset.f]=el.dataset.f==='qty'?Number(el.value.replace(/,/g,'')):el.value;renderConditions();saveState()}));
  productionCards.querySelectorAll('[data-flow-line]').forEach(el=>{const sync=()=>{const source=document.getElementById(`${el.dataset.flow}-${el.dataset.flowLine}`);if(source)source.value=el.value;saveState()};el.addEventListener('input',sync);el.addEventListener('blur',()=>{el.value=formatFlow(el.value);sync()})});
  productionCards.querySelectorAll('[data-line-record-product]').forEach(el=>el.addEventListener('change',()=>{const line=el.dataset.lineRecordProduct;const lineSelect=document.getElementById(`product-${line}`);if(lineSelect)lineSelect.value=el.value;applyProductToLine(line,el.value)}));
  productionCards.querySelectorAll('[data-new-product-test]').forEach(el=>el.addEventListener('click',()=>{const r=records.find(x=>x.id===el.dataset.newProductTest);if(!r)return;r.newProductTest=true;PROCESSES.forEach(p=>{r.conditions[p.key]={...(r.conditions[p.key]||{}),fillTop:'',fillMid:'',fillBottom:'',fill:'',time:'',temp:''}});renderRecords();renderConditions();saveState()}));
  productionCards.querySelectorAll('[data-bimodal]').forEach(el=>el.addEventListener('change',()=>{const r=records.find(x=>x.id===el.closest('.production-record').dataset.id);if(el.checked&&!r.bimodal)r.conditions.mainB={...r.conditions.mainA};r.bimodal=el.checked;renderConditions();saveState()}));
  productionCards.querySelectorAll('[data-process]').forEach(el=>el.addEventListener('change',()=>{const r=records.find(x=>x.id===el.closest('.production-record').dataset.id);if(el.dataset.process==='mainA'){r.enabled.mainA=el.checked;r.enabled.mainB=el.checked}else r.enabled[el.dataset.process]=el.checked;renderConditions();saveState()}));
  productionCards.querySelectorAll('[data-production-active]').forEach(el=>el.addEventListener('change',()=>{const line=el.dataset.productionActive;const base=document.querySelector(`#active-${line}`);if(base){base.checked=el.checked;base.closest('.line-card')?.classList.toggle('active',el.checked)}el.closest('.production-line-card').classList.toggle('active',el.checked);el.closest('.production-line-card').classList.toggle('inactive',!el.checked);renderConditions();saveState()}));
  productionCards.querySelectorAll('[data-add-line]').forEach(el=>el.addEventListener('click',()=>{records.push(blankRecord(el.dataset.addLine));renderRecords();renderConditions();saveState()}));
  productionCards.querySelectorAll('[data-delete]').forEach(el=>el.addEventListener('click',()=>{records=records.filter(x=>x.id!==el.dataset.delete);renderRecords();renderConditions();saveState()}));
}
const baseRenderRecords=renderRecords;
renderRecords=function(){baseRenderRecords();records.filter(r=>r.newProductTest).forEach(r=>{const select=productionCards.querySelector(`[data-id="${r.id}"] [data-line-record-product]`);if(!select||select.tagName!=='SELECT')return;const input=document.createElement('input');input.className=select.className;input.type='text';input.dataset.lineRecordProduct=select.dataset.lineRecordProduct;input.value=r.product||'';input.placeholder='신제품명 직접 입력';input.addEventListener('input',()=>{r.product=input.value;saveState()});input.addEventListener('blur',()=>{r.product=input.value.trim()||'신제품';input.value=r.product;saveState();renderConditions()});select.replaceWith(input)})};
document.addEventListener('click',event=>{const button=event.target.closest('[data-new-product-test]');if(!button)return;setTimeout(()=>{const r=records.find(x=>x.id===button.dataset.newProductTest),select=r&&productionCards.querySelector(`[data-id="${r.id}"] [data-line-record-product]`);if(!r?.newProductTest||!select||select.tagName!=='SELECT')return;const input=document.createElement('input');input.className=select.className;input.type='text';input.dataset.lineRecordProduct=select.dataset.lineRecordProduct;input.value=r.product||'';input.placeholder='신제품명 직접 입력';input.addEventListener('input',()=>{r.product=input.value;saveState()});input.addEventListener('blur',()=>{r.product=input.value.trim()||'신제품';input.value=r.product;saveState();renderConditions()});select.replaceWith(input);input.focus();input.select()},0)});
function refreshFillAverage(recordId,processKey){const r=records.find(x=>x.id===recordId);if(!r)return;const c=r.conditions[processKey];c.fill=(Number(c.fillTop||0)+Number(c.fillMid||0)+Number(c.fillBottom||0))/3;const avg=conditionCards.querySelector(`[data-average="${recordId}"][data-p="${processKey}"]`);if(avg)avg.innerHTML=`<small>평균 충진량</small><strong>${fmt(c.fill,1)} kg</strong>`;if(processKey==='mainA'){r.conditions.mainB.fillTop=c.fillTop;r.conditions.mainB.fillMid=c.fillMid;r.conditions.mainB.fillBottom=c.fillBottom;r.conditions.mainB.fill=c.fill}}
function renderConditions(){const lineState=getLineState();const visibleRecords=records.filter(r=>lineState[r.line]?.active);conditionCards.innerHTML=visibleRecords.length?visibleRecords.map(r=>{const enabledProcesses=INPUT_PROCESSES.filter(p=>p.key==='mainA'?r.enabled.mainA&&r.enabled.mainB:r.enabled[p.key]);return `<div class="condition-card"><div class="condition-card-title"><div><h4>${r.line} · ${r.product}</h4><small>${r.start} ~ ${r.end}</small></div><span class="condition-summary">${enabledProcesses.length}개 공정</span></div>${enabledProcesses.length?`<div class="condition-process-list">${enabledProcesses.map(p=>{const c=r.conditions[p.key];return `<div class="condition-process-group"><div class="condition-process-header"><strong>${p.inputName||p.name}</strong><span>${p.inlet}/${p.outlet} Hz</span></div><div class="fill-row"><label><span>상단</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="fillTop" type="number" step="0.1" value="${c.fillTop}"></label><label><span>중단</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="fillMid" type="number" step="0.1" value="${c.fillMid}"></label><label><span>하단</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="fillBottom" type="number" step="0.1" value="${c.fillBottom}"></label><div class="average-fill" data-average="${r.id}" data-p="${p.key}"><small>평균 충진량</small><strong>${fmt(c.fill,1)} kg</strong></div></div><div class="condition-secondary"><label><span>소성시간 (hr)</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="time" type="number" step="0.1" value="${c.time}"></label><label><span>로 온도 (°C)</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="temp" type="number" step="1" value="${c.temp}"></label></div></div>`}).join('')}</div>`:'<p class="muted">생산기간 및 생산량 입력에서 운전 공정을 선택하세요.</p>'}</div>`}).join(''):'<p class="muted">생산기간 및 생산량 입력에서 가동 라인을 체크하면 공정별 운전조건이 표시됩니다.</p>';conditionCards.querySelectorAll('[data-cid]').forEach(el=>el.addEventListener('input',()=>{const r=records.find(x=>x.id===el.dataset.cid);const v=Number(el.value);r.conditions[el.dataset.p][el.dataset.c]=v;if(el.dataset.c.startsWith('fill'))refreshFillAverage(r.id,el.dataset.p);if(el.dataset.p==='mainA'&&el.dataset.c.startsWith('fill'))refreshFillAverage(r.id,'mainB');if(el.dataset.p==='mainA'&&!el.dataset.c.startsWith('fill'))r.conditions.mainB[el.dataset.c]=v;saveState()}))}
const trainedModels={...(window.POWER_MODELS?.models||{}),...(window.POWER_MODELS_UTILITY_V4||{})};
function polynomialInput(model,season,numbers){const base=[...model.levels.map(v=>season===v?1:0),...numbers],out=[...base];for(let i=0;i<base.length;i++)for(let j=i;j<base.length;j++)out.push(base[i]*base[j]);return out.map((v,j)=>(v-(model.mu[j]??0))/(model.sd[j]||1))}
function predictModelClass(modelKey,season,numbers){const m=trainedModels[modelKey];if(!m)return {classNo:1,median:0,range:'모델 미연결',idx:0};const x=polynomialInput(m,season,numbers);const scores=m.W.map((w,c)=>m.B[c]+w.reduce((s,v,j)=>s+v*x[j],0)),idx=scores.indexOf(Math.max(...scores));return {classNo:idx+1,idx,median:(modelSettings[modelKey]?.medians?.[idx]??m.medians[idx]),range:m.ranges[idx]||`${m.bounds[idx-1]||0} 초과`,scores}}
function sharedCondition(rec,proc){return proc.key==='mainB'?rec.conditions.mainA:rec.conditions[proc.key]}
// 본소성A/B는 동일 설비이므로 본소성A/B 통합 모델(현재 mainA 모델)을 함께 사용한다.
function predictFurnace(rec,proc,days,season=seasonFromMonth(monthPicker.value)){const c=sharedCondition(rec,proc),modelKey=(proc.key==='mainA'||proc.key==='mainB')?'mainA':proc.key,pred=predictModelClass(modelKey,season,[Number(c.fill),Number(c.time),Number(c.temp),proc.inlet,proc.outlet]);return {classNo:pred.classNo,median:pred.median,range:pred.range,energy:pred.median*days,process:proc.name} }
function predictUtilityDaily(season,cfaTotal,airTotal,lineCount){const out={};[['airCompressor','Air Compressor'],['refrigeratedDryer','냉동식 Dryer'],['adsorptionDryer','흡착식 Dryer'],['co2Removal','CO2 Removal']].forEach(([key,name])=>{const pred=predictModelClass(key,season,[cfaTotal,airTotal,lineCount]);out[name]={...pred,kwh:pred.median}});return out}
function monthDates(month){const [y,m]=month.split('-').map(Number),last=new Date(y,m,0).getDate();return Array.from({length:last},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`)}
function calculate(){const lineState=getLineState(),active=LINES.filter(l=>lineState[l].active);if(!records.length){alert('생산 기록을 하나 이상 추가해주세요.');return}const month=monthPicker.value,days=monthDates(month),recordDates=new Map(records.map(r=>[r.id,dateSet(r.start,r.end,month)])),detailMap=new Map(),furnaceByLine=Object.fromEntries(active.map(l=>[l,0])),auxByLine=Object.fromEntries(active.map(l=>[l,0])),util={'Air Compressor':0,'냉동식 Dryer':0,'흡착식 Dryer':0,'CO2 Removal':0};let airTotal=0;records.filter(r=>lineState[r.line]?.active).forEach(r=>detailMap.set(r.id,{r,days:0,furnace:0,aux:0,utility:0,predictions:PROCESSES.filter(p=>r.enabled[p.key]).map(p=>predictFurnace(r,p,1))}));for(const day of days){const activeEntries=[...detailMap.values()].filter(x=>recordDates.get(x.r.id)?.has(day));const activeLines=[...new Set(activeEntries.map(x=>x.r.line))];if(!activeLines.length)continue;const season=seasonFromMonth(day),cfaTotal=activeLines.reduce((s,l)=>s+Number(lineState[l].cfa||0),0),cdaTotal=activeLines.reduce((s,l)=>s+Number(lineState[l].cda||0),0),airDay=cfaTotal+cdaTotal;airTotal+=airDay;const utilPred=predictUtilityDaily(season,cfaTotal,airDay,activeLines.length),utilDay=Object.fromEntries(Object.entries(utilPred).map(([k,v])=>[k,v.kwh]));Object.keys(util).forEach(k=>util[k]+=utilDay[k]||0);const furnaceDayByLine=Object.fromEntries(activeLines.map(l=>[l,0])),utilityBasisDayByLine=Object.fromEntries(activeLines.map(l=>[l,0]));activeEntries.forEach(x=>{x.days+=1;const procPred=PROCESSES.filter(p=>x.r.enabled[p.key]).map(p=>predictFurnace(x.r,p,1,season));x._dayFurnace=procPred.reduce((s,p)=>s+p.energy,0);x._dayUtilityBasis=procPred.filter(p=>['예비소성','본소성A','본소성B'].includes(p.process)).reduce((s,p)=>s+p.energy,0);x.furnace+=x._dayFurnace;x.aux+=AUX_DAILY_KWH[x.r.line]||12000;furnaceDayByLine[x.r.line]+=x._dayFurnace;utilityBasisDayByLine[x.r.line]+=x._dayUtilityBasis;x.predictions=procPred});const plantUtilityBasis=Object.values(utilityBasisDayByLine).reduce((s,v)=>s+v,0),utilityDayTotal=Object.values(utilDay).reduce((s,v)=>s+v,0);activeEntries.forEach(x=>{const lineShare=plantUtilityBasis?utilityBasisDayByLine[x.r.line]/plantUtilityBasis:0;const sameLineEntries=activeEntries.filter(y=>y.r.line===x.r.line),sameLineBasis=sameLineEntries.reduce((s,y)=>s+(y._dayUtilityBasis||0),0),productShare=sameLineBasis?(x._dayUtilityBasis||0)/sameLineBasis:0;x.utility+=utilityDayTotal*lineShare*productShare});Object.entries(furnaceDayByLine).forEach(([line,v])=>furnaceByLine[line]+=v);activeEntries.forEach(x=>{x.total=x.furnace+x.aux+x.utility})}const details=[...detailMap.values()].filter(x=>x.days>0);details.forEach(x=>{x.intensity=x.r.qty?x.total/x.r.qty:0;delete x._dayFurnace;delete x._dayUtilityBasis});const utilTotal=Object.values(util).reduce((s,v)=>s+v,0),totalFurnace=Object.values(furnaceByLine).reduce((s,v)=>s+v,0);lastResult={details,util,airTotal,totalFurnace,utilTotal,furnaceByLine,auxByLine};renderResults();saveState()}
function renderTariffEstimate(kwh){const panel=document.getElementById('tariffPanel');if(!panel)return;const t=calculateTariff(monthPicker.value,kwh);panel.innerHTML=`<div class="tariff-total"><small>${monthPicker.value} · ${t.season} · 예상 총 전력요금</small><strong>${fmt(t.total,0)}원</strong><span>예상 사용량 ${fmt(kwh,0)} kWh · 요금적용전력 ${fmt(t.chargePower,0)} kW</span></div><div class="tariff-lines"><div class="tariff-line"><small>기본요금</small><strong>${fmt(t.baseCharge,0)}원</strong></div><div class="tariff-line"><small>전력 사용요금</small><strong>${fmt(t.usageCharge,0)}원</strong></div><div class="tariff-line"><small>기후환경·연료비</small><strong>${fmt(t.climateCharge+t.fuelCharge,0)}원</strong></div><div class="tariff-line"><small>전력기금·부가세</small><strong>${fmt(t.fund+t.vat,0)}원</strong></div><p class="tariff-note">파일의 부하 비율(중간 32%·최대 18%·경부하 50%)과 선택 월의 계절별 단가를 적용했습니다. 역률요금은 입력값이 없어 0원으로 계산합니다.</p></div>`}
function renderResults(){const {details,totalFurnace,utilTotal}=lastResult;const total=details.reduce((s,x)=>s+x.total,0),qty=details.reduce((s,x)=>s+Number(x.r.qty||0),0),auxTotal=details.reduce((s,x)=>s+x.aux,0),directTotal=totalFurnace+auxTotal;kpiGrid.innerHTML=[['총 전력량',fmt(total),'kWh'],['총 생산량',fmt(qty,0),'kg'],['전력 원단위',fmt(qty?total/qty:0,3),'kWh/kg'],['공무동 예측',fmt(utilTotal),'kWh']].map(x=>`<div class="kpi"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${x[1]}<span class="kpi-unit">${x[2]}</span></div></div>`).join('');renderTariffEstimate(total);resultBody.innerHTML=details.map(x=>`<tr><td>${x.r.line}</td><td>${x.r.product}</td><td>${fmt(x.r.qty,0)}</td><td>${fmt(x.furnace)}</td><td>${fmt(x.aux)}</td><td>${fmt(x.utility)}</td><td>${fmt(x.total)}</td><td>${fmt(x.intensity,3)}</td></tr>`).join('');status('계산 완료',true);renderPowerComposition(directTotal,utilTotal,total);renderDonut(details);renderBars(details)}
function renderPowerComposition(directTotal,utilityTotal,total){const directPct=total?directTotal/total*100:0,utilityPct=total?utilityTotal/total*100:0;powerComposition.innerHTML=`<div class="composition-total"><strong>총 ${fmt(total)} kWh</strong><span>제품 생산에 배부되는 전체 전력</span></div><div class="stacked-power-bar" aria-label="설비 직접전력 ${fmt(directPct,1)}%, 공무동(유틸동) 전력 ${fmt(utilityPct,1)}%"><div class="power-segment direct" style="width:${directPct}%"><span>설비 직접전력</span><b>${fmt(directPct,1)}%</b></div><div class="power-segment utility" style="width:${utilityPct}%"><span>공무동(유틸동) 전력</span><b>${fmt(utilityPct,1)}%</b></div></div><div class="composition-legend"><div><i class="legend-dot direct-dot"></i><span><strong>설비 직접전력</strong><small>로 전력 + 外 설비 · ${fmt(directTotal)} kWh</small></span></div><div><i class="legend-dot utility-dot"></i><span><strong>공무동(유틸동) 전력</strong><small>예비소성·본소성 전력 비율 배부 · ${fmt(utilityTotal)} kWh</small></span></div></div>`}
function renderDonut(details){const by={};details.forEach(x=>by[x.r.line]=(by[x.r.line]||0)+x.total);const vals=Object.entries(by), sum=vals.reduce((s,x)=>s+x[1],0);let cursor=0;const stops=vals.map(([line,v],i)=>{const a=cursor;cursor+=v/sum*360;return `${palette[i%palette.length]} ${a}deg ${cursor}deg`}).join(',');donutChart.innerHTML=`<div class="donut" style="background:conic-gradient(${stops})"><div class="donut-center">${fmt(sum)}<small>총 kWh</small></div></div><div class="legend">${vals.map(([line,v],i)=>`<div class="legend-row"><i class="legend-dot" style="background:${palette[i%palette.length]}"></i>${line} · ${fmt(v/sum*100,1)}%</div>`).join('')}</div>`}
function renderBars(details){const by={};details.forEach(x=>{const p=x.r.product;if(!by[p])by[p]={e:0,q:0};by[p].e+=x.total;by[p].q+=Number(x.r.qty||0)});const vals=Object.entries(by).map(([p,v])=>[p,v.q?v.e/v.q:0]);const max=Math.max(...vals.map(x=>x[1]),1);barChart.innerHTML=vals.map(([p,v])=>`<div class="bar-row"><strong>${p}</strong><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><span class="bar-value">${fmt(v,3)}</span></div>`).join('')}
function status(text,ready=false){calculationStatus.textContent=text;calculationStatus.classList.toggle('ready',ready)}
function renderSettings(){modelSettingsEl.innerHTML=PROCESSES.flatMap(p=>(modelSettings[p.key]?.medians||p.medians).map((v,i)=>`<div class="setting-card"><strong>${p.name} · Class ${i+1}</strong><label>대표 중앙값 (kWh)<input type="number" data-setting="${p.key}" data-index="${i}" value="${v}"></label></div>`)).join('');modelSettingsEl.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener('change',()=>{modelSettings[el.dataset.setting].medians[Number(el.dataset.index)]=Number(el.value);localStorage.setItem('power-model-settings-v2',JSON.stringify(modelSettings));status('모델 설정 저장됨',true)}))}
function renderProductSettings(){const processFields=[['pre','예비소성'],['mainA','본소성A/B'],['heat','열처리']];productSettingsEl.innerHTML=PRODUCT_OPTIONS.map(product=>{const t=productSettings[product]||PRODUCT_TEMPLATES[product];return `<div class="product-setting-card"><div class="product-setting-title"><strong>${product}</strong><span>제품 기본조건</span></div><div class="product-flow-fields"><label>CFA 유량<input type="number" min="0" step="0.1" data-product-setting="${product}" data-setting-field="cfa" value="${t.cfa}"></label><label>CDA 유량<input type="number" min="0" step="0.1" data-product-setting="${product}" data-setting-field="cda" value="${t.cda}"></label></div>${processFields.map(([key,label])=>{const c=t.conditions[key]||t.conditions.mainA||{fillTop:0,fillMid:0,fillBottom:0,time:0,temp:0};const enabled=t.enabled[key]!==false;return `<div class="product-process-setting"><div class="product-process-heading"><strong>${label}</strong><label><input type="checkbox" data-product-setting="${product}" data-setting-process="${key}" ${enabled?'checked':''}> 적용</label></div><div class="product-condition-fields"><label>상단<input type="number" step="0.1" data-product-setting="${product}" data-setting-process="${key}" data-setting-field="fillTop" value="${c.fillTop??0}"></label><label>중단<input type="number" step="0.1" data-product-setting="${product}" data-setting-process="${key}" data-setting-field="fillMid" value="${c.fillMid??0}"></label><label>하단<input type="number" step="0.1" data-product-setting="${product}" data-setting-process="${key}" data-setting-field="fillBottom" value="${c.fillBottom??0}"></label><label>소성시간 (hr)<input type="number" step="0.1" data-product-setting="${product}" data-setting-process="${key}" data-setting-field="time" value="${c.time??0}"></label><label>로 온도 (°C)<input type="number" step="1" data-product-setting="${product}" data-setting-process="${key}" data-setting-field="temp" value="${c.temp??0}"></label></div></div>`}).join('')}</div>`}).join('');productSettingsEl.querySelectorAll('[data-product-setting]').forEach(el=>el.addEventListener('change',()=>{const product=el.dataset.productSetting,t=productSettings[product];if(el.dataset.settingField==='cfa'||el.dataset.settingField==='cda')t[el.dataset.settingField]=Number(el.value)||0;else if(el.dataset.settingProcess){const key=el.dataset.settingProcess;if(el.dataset.settingField)t.conditions[key][el.dataset.settingField]=Number(el.value)||0;else if(el.type==='checkbox'){t.enabled[key]=el.checked;if(key==='mainA')t.enabled.mainB=el.checked}}saveProductSettings();LINES.forEach(line=>{if(document.getElementById(`product-${line}`)?.value===product)applyProductToLine(line,product)});status(`${product} 제품조건 저장됨`,true)}))}
function downloadExcel(){if(!lastResult){alert('먼저 산정 갱신을 눌러 계산하세요.');return}const resultRows=[['라인','제품','열처리 생산량(kg)','로 전력(kWh)','外 설비(kWh)','공무동(유틸동) 전력(kWh)','총전력(kWh)','전력원단위(kWh/kg)'],...lastResult.details.map(x=>[x.r.line,x.r.product,x.r.qty,x.furnace,x.aux,x.utility,x.total,x.intensity])];const inputRows=[['라인','제품','시작일','종료일','열처리 생산량(kg)','예비소성','본소성A/B','열처리'],...records.map(r=>[r.line,r.product,r.start,r.end,r.qty,...INPUT_PROCESSES.map(p=>(p.key==='mainA'?r.enabled.mainA&&r.enabled.mainB:r.enabled[p.key])?'생산':'미생산')])];const table=(title,rows)=>`<h2>${title}</h2><table border="1">${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</table>`;const html=`<html><meta charset="UTF-8"><body>${table(`전력 배부 결과 · ${monthPicker.value}`,resultRows)}${table('입력 생산 기록',inputRows)}</body></html>`;const blob=new Blob([html],{type:'application/vnd.ms-excel'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`전력배부결과_${monthPicker.value}.xls`;a.click();URL.revokeObjectURL(a.href)}
function activateTab(key){document.querySelectorAll('[data-tab-switch]').forEach(btn=>btn.classList.toggle('active',btn.dataset.tabSwitch===key));document.querySelectorAll('[data-tab-content]').forEach(panel=>panel.classList.toggle('is-hidden',panel.dataset.tabContent!==key))}
function init(){const saved=loadState();monthPicker.value=saved?.month||'2026-07';seasonBadge.textContent=seasonFromMonth(monthPicker.value);renderLines(saved?.lines||{});records=normalizeRecords(saved?.records||LINES.map(line=>blankRecord(line)));renderRecords();renderConditions();renderProductSettings();renderSettings();activateTab('production');document.querySelectorAll('[data-tab-switch]').forEach(btn=>btn.addEventListener('click',()=>activateTab(btn.dataset.tabSwitch)));calculateBtn.addEventListener('click',calculate);downloadBtn.addEventListener('click',downloadExcel);monthPicker.addEventListener('change',()=>{seasonBadge.textContent=seasonFromMonth(monthPicker.value);renderRecords();renderConditions();saveState();status('산정 대상 월 변경 · 산정 갱신 필요')});resetBtn.addEventListener('click',()=>{if(confirm('입력값과 산정 결과를 초기화할까요?')){localStorage.removeItem(STORAGE_KEY);records=LINES.map(line=>blankRecord(line));renderLines();renderRecords();renderConditions();lastResult=null;status('입력 후 산정 갱신 필요');kpiGrid.innerHTML='';resultBody.innerHTML='';donutChart.innerHTML='';barChart.innerHTML=''}})}
const lineGrid=document.getElementById('lineGrid'),productionCards=document.getElementById('productionCards'),conditionCards=document.getElementById('conditionCards'),monthPicker=document.getElementById('monthPicker'),seasonBadge=document.getElementById('seasonBadge'),calculateBtn=document.getElementById('calculateBtn'),downloadBtn=document.getElementById('downloadBtn'),resetBtn=document.getElementById('resetBtn'),kpiGrid=document.getElementById('kpiGrid'),powerComposition=document.getElementById('powerComposition'),resultBody=document.getElementById('resultBody'),donutChart=document.getElementById('donutChart'),barChart=document.getElementById('barChart'),calculationStatus=document.getElementById('calculationStatus'),modelSettingsEl=document.getElementById('modelSettings'),productSettingsEl=document.getElementById('productSettings');
init();

// 월 단위 공무동 배부: 대표 일 공무동 전력 × 해당 월 일수 × 예비소성·본소성 전력 비율
function calculate(){
  const lineState=getLineState(), month=monthPicker.value, monthDays=monthDates(month);
  if(!records.length){alert('생산 기록을 하나 이상 추가해주세요.');return}
  const detailMap=new Map();
  records.filter(r=>lineState[r.line]?.active).forEach(r=>{
    const operatingDays=daysInclusive(r.start,r.end,month);
    if(operatingDays>0) detailMap.set(r.id,{r,days:operatingDays,furnace:0,aux:0,utility:0,predictions:[]});
  });
  const activeLines=[...new Set([...detailMap.values()].map(x=>x.r.line))];
  if(!activeLines.length){alert('선택한 월에 생산기간이 포함된 가동 라인이 없습니다.');return}
  const season=seasonFromMonth(month),cfaTotal=activeLines.reduce((s,l)=>s+Number(lineState[l].cfa||0),0),cdaTotal=activeLines.reduce((s,l)=>s+Number(lineState[l].cda||0),0),airDay=cfaTotal+cdaTotal,lineCount=activeLines.length;
  const utilityDaily=predictUtilityDaily(season,cfaTotal,airDay,lineCount);
  const util=Object.fromEntries(Object.entries(utilityDaily).map(([k,v])=>[k,v.kwh*monthDays.length]));
  const furnaceByLine=Object.fromEntries(activeLines.map(l=>[l,0])),utilityBasisByLine=Object.fromEntries(activeLines.map(l=>[l,0]));
  detailMap.forEach(x=>{
    const procPred=PROCESSES.filter(p=>x.r.enabled[p.key]).map(p=>predictFurnace(x.r,p,1,season));
    const dailyFurnace=procPred.reduce((s,p)=>s+p.energy,0),dailyBasis=procPred.filter(p=>['예비소성','본소성A','본소성B'].includes(p.process)).reduce((s,p)=>s+p.energy,0);
    x._monthlyBasis=dailyBasis*x.days;x.furnace=dailyFurnace*x.days;x.aux=(AUX_DAILY_KWH[x.r.line]||12000)*x.days;x.predictions=procPred;
    furnaceByLine[x.r.line]+=x.furnace;utilityBasisByLine[x.r.line]+=x._monthlyBasis;
  });
  const plantBasis=Object.values(utilityBasisByLine).reduce((s,v)=>s+v,0),utilTotal=Object.values(util).reduce((s,v)=>s+v,0);
  detailMap.forEach(x=>{
    const lineShare=plantBasis?utilityBasisByLine[x.r.line]/plantBasis:0,sameLineBasis=[...detailMap.values()].filter(y=>y.r.line===x.r.line).reduce((s,y)=>s+y._monthlyBasis,0),productShare=sameLineBasis?x._monthlyBasis/sameLineBasis:0;
    x.utility=utilTotal*lineShare*productShare;x.total=x.furnace+x.aux+x.utility;x.intensity=x.r.qty?x.total/x.r.qty:0;delete x._monthlyBasis;
  });
  const details=[...detailMap.values()],totalFurnace=Object.values(furnaceByLine).reduce((s,v)=>s+v,0),airTotal=airDay*monthDays.length;
  lastResult={details,util,airTotal,totalFurnace,utilTotal,furnaceByLine,auxByLine:{}};renderResults();saveState();
}

function renderResults(){
  const {details,totalFurnace,utilTotal}=lastResult;
  const total=details.reduce((s,x)=>s+x.total,0),qty=details.reduce((s,x)=>s+Number(x.r.qty||0),0),auxTotal=details.reduce((s,x)=>s+x.aux,0),directTotal=totalFurnace+auxTotal;
  kpiGrid.innerHTML=[['총 전력량',fmt(total),'kWh'],['총 생산량',fmt(qty,0),'kg'],['전력 원단위',fmt(qty?total/qty:0,3),'kWh/kg'],['공무동 예측',fmt(utilTotal),'kWh']].map(x=>`<div class="kpi"><div class="kpi-label">${x[0]}</div><div class="kpi-value">${x[1]}<span class="kpi-unit">${x[2]}</span></div></div>`).join('');
  renderTariffEstimate(total);
  resultBody.closest('table').querySelector('thead tr').innerHTML='<th>라인</th><th>제품</th><th>열처리 생산량 (kg)</th><th>로 전력</th><th>外 설비(집진기 포함)</th><th>공무동(유틸동) 전력</th><th>총 전력</th><th>전력 원단위</th>';
  resultBody.innerHTML=details.map(x=>`<tr><td>${x.r.line}</td><td>${x.r.product}</td><td>${fmt(x.r.qty,0)}</td><td>${fmt(x.furnace)}</td><td>${fmt(x.aux)}</td><td>${fmt(x.utility)}</td><td>${fmt(x.total)}</td><td>${fmt(x.intensity,3)}</td></tr>`).join('');
  status('계산 완료',true);renderPowerComposition(directTotal,utilTotal,total);renderDonut(details);renderBars(details);
}

// 날짜별 가동라인 수와 날짜별 CFA·CDA를 반영하는 월 집계 로직
function calculate(){
  const lineState=getLineState(),active=LINES.filter(l=>lineState[l].active);
  if(!records.length){alert('생산 기록을 하나 이상 추가해주세요.');return}
  const month=monthPicker.value,days=monthDates(month),recordDates=new Map(records.map(r=>[r.id,fullDateSet(r.start,r.end)])),detailMap=new Map(),furnaceByLine=Object.fromEntries(active.map(l=>[l,0])),auxByLine=Object.fromEntries(active.map(l=>[l,0])),util={'Air Compressor':0,'냉동식 Dryer':0,'흡착식 Dryer':0,'CO2 Removal':0};
  let airTotal=0;
  records.filter(r=>lineState[r.line]?.active).forEach(r=>detailMap.set(r.id,{r,days:0,furnace:0,aux:0,utility:0,utilityBasisTotal:0,heatQty:Number(r.qty||0),heatFurnace:0,predictions:[]}));
  for(const day of days){
    const activeEntries=[...detailMap.values()].filter(x=>{const dates=recordDates.get(x.r.id);return PROCESSES.some(p=>x.r.enabled[p.key]&&dates?.has(shiftedDateKey(day,PROCESS_LAG_DAYS[p.key]))) }),activeLines=[...new Set(activeEntries.map(x=>x.r.line))];
    if(!activeLines.length){
      const base=baseUtilityForDay(day);
      Object.keys(util).forEach(k=>util[k]+=base?.[k]||0);
      continue;
    }
    const season=seasonFromMonth(day),cfaTotal=activeLines.reduce((s,l)=>s+Number(lineState[l].cfa||0),0),cdaTotal=activeLines.reduce((s,l)=>s+Number(lineState[l].cda||0),0),airDay=cfaTotal+cdaTotal;
    airTotal+=airDay;
    const utilPred=predictUtilityDaily(season,cfaTotal,airDay,activeLines.length),utilDay=Object.fromEntries(Object.entries(utilPred).map(([k,v])=>[k,v.kwh]));
    Object.keys(util).forEach(k=>util[k]+=utilDay[k]||0);
    const furnaceDayByLine=Object.fromEntries(activeLines.map(l=>[l,0])),utilityBasisDayByLine=Object.fromEntries(activeLines.map(l=>[l,0]));
    activeEntries.forEach(x=>{
      x.days+=1;
      const procPred=PROCESSES.filter(p=>x.r.enabled[p.key]&&recordDates.get(x.r.id)?.has(shiftedDateKey(day,PROCESS_LAG_DAYS[p.key]))).map(p=>predictFurnace(x.r,p,1,season)),dailyFurnace=procPred.reduce((s,p)=>s+p.energy,0),dailyBasis=procPred.filter(p=>['예비소성','본소성A','본소성B'].includes(p.process)).reduce((s,p)=>s+p.energy,0);
      const dailyHeat=procPred.filter(p=>p.process==='열처리').reduce((s,p)=>s+p.energy,0),dustDaily=DUST_DAILY_KWH[x.r.line]||0; x._dayFurnace=dailyFurnace;x._dayUtilityBasis=dailyBasis;x.furnace+=dailyFurnace;x.utilityBasisTotal+=dailyBasis;x.heatFurnace+=dailyHeat;x.aux+=(AUX_DAILY_KWH[x.r.line]||12000)+dustDaily;x.dust=(x.dust||0)+dustDaily;x.predictions=procPred;furnaceDayByLine[x.r.line]+=dailyFurnace;utilityBasisDayByLine[x.r.line]+=dailyBasis;
    });
    const plantUtilityBasis=Object.values(utilityBasisDayByLine).reduce((s,v)=>s+v,0),utilityDayTotal=Object.values(utilDay).reduce((s,v)=>s+v,0);
    activeEntries.forEach(x=>{
      const lineShare=plantUtilityBasis?utilityBasisDayByLine[x.r.line]/plantUtilityBasis:0,sameLineEntries=activeEntries.filter(y=>y.r.line===x.r.line),sameLineBasis=sameLineEntries.reduce((s,y)=>s+(y._dayUtilityBasis||0),0),productShare=sameLineBasis?(x._dayUtilityBasis||0)/sameLineBasis:0;
      x.utility+=utilityDayTotal*lineShare*productShare;
    });
    Object.entries(furnaceDayByLine).forEach(([line,v])=>furnaceByLine[line]+=v);
  }
  const details=[...detailMap.values()].filter(x=>x.days>0);
  const utilTotal=Object.values(util).reduce((s,v)=>s+v,0),allocatedUtility=details.reduce((s,x)=>s+x.utility,0),unallocatedUtility=Math.max(0,utilTotal-allocatedUtility),basisTotal=details.reduce((s,x)=>s+x.utilityBasisTotal,0);
  details.forEach(x=>{const share=basisTotal?x.utilityBasisTotal/basisTotal:(details.length?1/details.length:0);x.utility+=unallocatedUtility*share;x.total=x.furnace+x.aux+x.utility;x.intensity=x.r.qty?x.total/x.r.qty:0;x.heatIntensity=x.heatQty?x.heatFurnace/x.heatQty:0;delete x.utilityBasisTotal;delete x._dayFurnace;delete x._dayUtilityBasis});
  const totalFurnace=Object.values(furnaceByLine).reduce((s,v)=>s+v,0);
  lastResult={details,util,airTotal,totalFurnace,utilTotal,furnaceByLine,auxByLine};renderResults();saveState();
}

function refreshFillAverage(recordId,processKey){const r=records.find(x=>x.id===recordId);if(!r)return;const c=r.conditions[processKey];c.fill=(Number(c.fillTop||0)+Number(c.fillMid||0)+Number(c.fillBottom||0))/3;const avg=conditionCards.querySelector(`[data-average="${recordId}"][data-p="${processKey}"]`);if(avg)avg.innerHTML=`<small>평균 충진량</small><strong>${fmt(c.fill,1)} kg</strong>`;if(processKey==='mainA'&&!r.bimodal){r.conditions.mainB.fillTop=c.fillTop;r.conditions.mainB.fillMid=c.fillMid;r.conditions.mainB.fillBottom=c.fillBottom;r.conditions.mainB.fill=c.fill}}
function sharedCondition(rec,proc){return proc.key==='mainB'&&rec.bimodal?rec.conditions.mainB:proc.key==='mainB'?rec.conditions.mainA:rec.conditions[proc.key]}
function renderConditions(){const lineState=getLineState(),visibleRecords=records.filter(r=>lineState[r.line]?.active);conditionCards.innerHTML=visibleRecords.length?visibleRecords.map(r=>{const conditionProcesses=r.bimodal?PROCESSES.filter(p=>p.key==='pre'||p.key==='heat'||(p.key==='mainA'&&r.enabled.mainA&&r.enabled.mainB)||(p.key==='mainB'&&r.enabled.mainA&&r.enabled.mainB)):INPUT_PROCESSES.filter(p=>p.key==='mainA'?r.enabled.mainA&&r.enabled.mainB:r.enabled[p.key]);return `<div class="condition-card"><div class="condition-card-title"><div><h4>${r.line} · ${r.product}</h4><small>${r.start} ~ ${r.end}</small></div><span class="condition-summary">${conditionProcesses.length}개 공정${r.bimodal?' · Bimodal':''}</span></div>${conditionProcesses.length?`<div class="condition-process-list">${conditionProcesses.map(p=>{const c=r.conditions[p.key];return `<div class="condition-process-group"><div class="condition-process-header"><strong>${p.inputName||p.name}</strong><span>${p.inlet}/${p.outlet} Hz</span></div><div class="fill-row"><label><span>상단</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="fillTop" type="number" step="0.1" value="${c.fillTop}"></label><label><span>중단</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="fillMid" type="number" step="0.1" value="${c.fillMid}"></label><label><span>하단</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="fillBottom" type="number" step="0.1" value="${c.fillBottom}"></label><div class="average-fill" data-average="${r.id}" data-p="${p.key}"><small>평균 충진량</small><strong>${fmt(c.fill,1)} kg</strong></div></div><div class="condition-secondary"><label><span>소성시간 (hr)</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="time" type="number" step="0.1" value="${c.time}"></label><label><span>로 온도 (°C)</span><input class="condition-input" data-cid="${r.id}" data-p="${p.key}" data-c="temp" type="number" step="1" value="${c.temp}"></label></div></div>`}).join('')}</div>`:'<p class="muted">생산기간 및 생산량 입력에서 운전 공정을 선택하세요.</p>'}</div>`}).join(''):'<p class="muted">생산기간 및 생산량 입력에서 가동 라인을 체크하면 공정별 운전조건이 표시됩니다.</p>';conditionCards.querySelectorAll('[data-cid]').forEach(el=>el.addEventListener('input',()=>{const r=records.find(x=>x.id===el.dataset.cid),v=Number(el.value);r.conditions[el.dataset.p][el.dataset.c]=v;if(el.dataset.c.startsWith('fill'))refreshFillAverage(r.id,el.dataset.p);if(el.dataset.p==='mainA'&&!r.bimodal&&!el.dataset.c.startsWith('fill'))r.conditions.mainB[el.dataset.c]=v;saveState()}))}

function markNewProductTestConditions(){records.filter(r=>r.newProductTest).forEach(r=>{const fields=conditionCards.querySelectorAll(`[data-cid="${r.id}"]`);fields.forEach(el=>{el.value='';el.closest('.condition-card')?.classList.add('new-product-test-card')});conditionCards.querySelectorAll(`[data-average="${r.id}"]`).forEach(el=>{el.innerHTML='<small>평균 충진량</small><strong>입력 필요</strong>'})})}
const _renderConditions=renderConditions;renderConditions=function(){_renderConditions();markNewProductTestConditions()};markNewProductTestConditions();
